//! MinIO bucket notification subscriber — NATS-based.
//!
//! MinIO publishes S3-compatible event notifications to a NATS subject
//! when configured via `mc admin config set notify_nats`. The observer
//! subscribes to that subject and converts each event into a `ChainEntry`.
//!
//! # Event format
//!
//! MinIO uses the standard S3 event notification JSON format:
//! ```json
//! {
//!   "EventName": "s3:ObjectCreated:Put",
//!   "Key": "uploads/users/42/avatar.jpg",
//!   "Records": [{
//!     "s3": {
//!       "bucket": { "name": "uploads" },
//!       "object": { "key": "users/42/avatar.jpg", "size": 12345, "eTag": "..." }
//!     }
//!   }]
//! }
//! ```
//!
//! # Trust model
//!
//! The bucket notifications are generated by *MinIO itself*, not by the
//! proxy. The proxy has no code path that suppresses or modifies them.
//! A compromised proxy could drop the NATS subject entirely (denial of
//! service), but cannot fabricate fake events — the observer would see
//! missing events, not forged ones.
//!
//! # Library
//!
//! [`async-nats`](https://crates.io/crates/async-nats) is the official
//! NATS.io Rust client, maintained by Synadia. Tokio-native, actively
//! updated (Jan 2026).

use crate::chain::ObserverChain;
use crate::config::MinioSubscriberConfig;
use futures::StreamExt;
use sha2::{Digest, Sha256};
use std::collections::HashMap;
use std::sync::Arc;
use std::time::Duration;
use tracing::{debug, error, info, warn};
use uninc_common::ActionType;

pub struct MinioSubscriber {
    cfg: MinioSubscriberConfig,
    chain: Arc<ObserverChain>,
}

impl MinioSubscriber {
    pub fn new(cfg: MinioSubscriberConfig, chain: Arc<ObserverChain>) -> Self {
        Self { cfg, chain }
    }

    /// Long-running subscriber loop with exponential backoff on failure.
    pub async fn run(self) {
        info!(
            nats_url = self.cfg.nats_url.as_str(),
            subject = self.cfg.subject.as_str(),
            "minio subscriber starting"
        );

        let mut backoff_secs = 1u64;
        loop {
            match self.connect_and_consume().await {
                Ok(()) => {
                    backoff_secs = 1;
                    tokio::time::sleep(Duration::from_secs(1)).await;
                }
                Err(e) => {
                    error!(
                        error = %e,
                        next_retry_secs = backoff_secs,
                        "minio subscriber errored, backing off"
                    );
                    tokio::time::sleep(Duration::from_secs(backoff_secs)).await;
                    backoff_secs = (backoff_secs * 2).min(60);
                }
            }
        }
    }

    /// Connect to NATS, subscribe to the MinIO notification subject,
    /// and process events until the subscription closes.
    async fn connect_and_consume(&self) -> anyhow::Result<()> {
        let chain = Arc::clone(&self.chain);

        // Connect to the deployment's internal NATS server (on the proxy VM).
        let nc = async_nats::connect(&self.cfg.nats_url).await?;
        info!(subject = self.cfg.subject.as_str(), "subscribed to MinIO notification subject");

        let mut subscriber = nc.subscribe(self.cfg.subject.clone()).await?;
        let mut event_count: u64 = 0;

        // Each NATS message payload is a MinIO S3 event notification JSON.
        while let Some(msg) = subscriber.next().await {
            let payload = std::str::from_utf8(&msg.payload);
            let json_str = match payload {
                Ok(s) => s,
                Err(e) => {
                    warn!(error = %e, "invalid UTF-8 in MinIO notification payload");
                    continue;
                }
            };

            // Parse the S3 event notification JSON.
            let event: serde_json::Value = match serde_json::from_str(json_str) {
                Ok(v) => v,
                Err(e) => {
                    warn!(error = %e, "failed to parse MinIO notification JSON");
                    continue;
                }
            };

            // Extract event name — e.g. "s3:ObjectCreated:Put", "s3:ObjectRemoved:Delete"
            let event_name = event
                .get("EventName")
                .and_then(|v| v.as_str())
                .unwrap_or("unknown");

            // Map S3 event name to our ActionType.
            let action = if event_name.contains("Created") || event_name.contains("Put") {
                ActionType::Write
            } else if event_name.contains("Removed") || event_name.contains("Delete") {
                ActionType::Delete
            } else if event_name.contains("Accessed") || event_name.contains("Get") || event_name.contains("Head") {
                ActionType::Read
            } else {
                debug!(event_name, "skipping unrecognized MinIO event");
                continue;
            };

            // Extract bucket and object details from Records[0].s3
            let record = event
                .get("Records")
                .and_then(|r| r.as_array())
                .and_then(|arr| arr.first());

            let s3_info = record.and_then(|r| r.get("s3"));

            let bucket = s3_info
                .and_then(|s| s.get("bucket"))
                .and_then(|b| b.get("name"))
                .and_then(|n| n.as_str())
                .unwrap_or("unknown");

            let object = s3_info.and_then(|s| s.get("object"));
            let key = object
                .and_then(|o| o.get("key"))
                .and_then(|k| k.as_str())
                .unwrap_or("unknown");
            let size = object
                .and_then(|o| o.get("size"))
                .and_then(|s| s.as_u64())
                .unwrap_or(0);
            let etag = object
                .and_then(|o| o.get("eTag"))
                .and_then(|e| e.as_str())
                .unwrap_or("");

            // Recover the actor marker the proxy attached on PUT via
            // the `x-amz-meta-uninc-actor` header. MinIO surfaces it
            // inside the notification JSON at `s3.object.userMetadata`.
            // MinIO versions have historically varied on the case of
            // the key name (lowercase `x-amz-meta-*` matches AWS S3;
            // capitalized `X-Amz-Meta-*` has appeared in some MinIO
            // versions — see minio/minio#6471 and minio/minio#10140).
            // We do a case-insensitive lookup on the final segment
            // `uninc-actor` to be robust across MinIO versions.
            //
            // When no marker is present (app-class upload, or a
            // primitive path that can't carry user-metadata like S3
            // DELETE), the pre-hash defaults to a placeholder that
            // HMACs to a well-formed but non-matching `actor_id_hash`.
            // See server/SPEC-DELTA.md §"Actor identity" for scope.
            let user_metadata = object.and_then(|o| o.get("userMetadata"));
            let actor_pre_hash = extract_uninc_actor(user_metadata)
                .unwrap_or_else(|| "observer:minio".to_string());

            // Build the chain entry fields.
            let resource = format!("{}/{}", bucket, key);
            let scope = format!("event: {}; size: {}; etag: {}", event_name, size, etag);

            let fingerprint = {
                let mut h = Sha256::new();
                h.update(format!("{}:{}", event_name, resource).as_bytes());
                let result: [u8; 32] = h.finalize().into();
                result
            };

            let metadata = Some(HashMap::from([
                ("source".to_string(), "minio_nats_notification".to_string()),
                ("event_name".to_string(), event_name.to_string()),
                ("bucket".to_string(), bucket.to_string()),
            ]));

            if let Err(e) = chain.append(
                "_deployment",
                actor_pre_hash,
                action,
                resource,
                scope,
                fingerprint,
                metadata,
            ).await {
                warn!(error = %e, "failed to append observer chain entry");
            }

            event_count += 1;
            if event_count % 100 == 0 {
                debug!(event_count, "processed MinIO notification events");
            }
        }

        info!(event_count, "NATS subscription ended");
        Ok(())
    }
}

/// Case-insensitive lookup for the `x-amz-meta-uninc-actor` value on a
/// MinIO notification's `userMetadata` JSON object.
///
/// MinIO's bucket-notification payload exposes custom metadata headers
/// under `s3.object.userMetadata`. The proxy writes the header as
/// `x-amz-meta-uninc-actor` (lowercase — AWS-S3-compatible canonical
/// form). MinIO has historically varied in how it stores metadata keys
/// (lowercase vs first-letter-capitalized — see minio/minio#6471) so we
/// search both the exact lowercase form and the canonical header
/// casing, and fall back to any key whose suffix is `uninc-actor`.
fn extract_uninc_actor(user_metadata: Option<&serde_json::Value>) -> Option<String> {
    let obj = user_metadata?.as_object()?;
    const CANDIDATES: &[&str] = &[
        "x-amz-meta-uninc-actor",
        "X-Amz-Meta-Uninc-Actor",
        "X-Amz-Meta-uninc-actor",
    ];
    for k in CANDIDATES {
        if let Some(v) = obj.get(*k).and_then(|v| v.as_str()) {
            return Some(v.to_string());
        }
    }
    // Final fallback: any key whose lowercase form ends in
    // `uninc-actor`. Defends against future MinIO casing drift.
    for (k, v) in obj.iter() {
        if k.to_ascii_lowercase().ends_with("uninc-actor") {
            if let Some(s) = v.as_str() {
                return Some(s.to_string());
            }
        }
    }
    None
}

#[cfg(test)]
mod tests {
    use super::*;
    use serde_json::json;

    #[test]
    fn extract_actor_lowercase_aws_canonical() {
        let md = json!({ "x-amz-meta-uninc-actor": "alice" });
        assert_eq!(
            extract_uninc_actor(Some(&md)),
            Some("alice".to_string())
        );
    }

    #[test]
    fn extract_actor_minio_capitalized() {
        let md = json!({ "X-Amz-Meta-Uninc-Actor": "bob" });
        assert_eq!(
            extract_uninc_actor(Some(&md)),
            Some("bob".to_string())
        );
    }

    #[test]
    fn extract_actor_absent_returns_none() {
        let md = json!({ "content-type": "image/png" });
        assert_eq!(extract_uninc_actor(Some(&md)), None);
    }

    #[test]
    fn extract_actor_handles_none_metadata() {
        assert_eq!(extract_uninc_actor(None), None);
    }

    #[test]
    fn extract_actor_suffix_fallback() {
        // Guards against future MinIO versions re-casing the prefix.
        let md = json!({ "X-AMZ-META-UNINC-ACTOR": "carol" });
        assert_eq!(
            extract_uninc_actor(Some(&md)),
            Some("carol".to_string())
        );
    }
}
