//! `observer` — the independent data-access transparency log observer.
//!
//! The observer runs on its own VM in a multi-VM topology, separate from
//! the proxy VM. It subscribes directly to each data primitive's *native*
//! replication/notification stream using read-only credentials provisioned
//! out-of-band — they must not be issued by the proxy:
//!
//! - **Postgres**: logical replication via `tokio-postgres` with
//!   `replication=database` and pgoutput protocol. Parses Relation,
//!   Insert, Update, Delete WAL messages.
//! - **MongoDB**: Change Streams via the official `mongodb` driver's
//!   `watch()` method. Handles replica set failover and resume tokens
//!   automatically.
//! - **MinIO/S3**: Bucket notifications via `async-nats`. MinIO publishes
//!   S3-compatible event JSON to a NATS subject; the observer subscribes
//!   and parses ObjectCreated/ObjectRemoved events.
//!
//! For each observed operation, the observer computes the same
//! `UNINC_CHAIN_V1` hash (via `chain_store::ChainEntry`) and appends the
//! entry to an independent deployment chain on its own local disk.
//!
//! The verification task (in `server/crates/verification`) then compares
//! the proxy's chain head against the observer's chain head. Any
//! divergence means either the proxy omitted an operation from the chain,
//! or the proxy fabricated an operation that never hit the database —
//! both of which are forensically significant and fire the failure handler
//! chain.
//!
//! # Why this is the real trust-story defense
//!
//! Multi-copy chain storage (fan-out from proxy to 3 replica chain-MinIOs)
//! does NOT defend against a compromised proxy, because the proxy controls
//! the fan-out — it can write consistent tampered data to all 3 replicas
//! and head comparison agrees. The only structural defense is an
//! *independent observer of the data path itself*: something that reads
//! the database's own replication stream (generated by Postgres / Mongo /
//! MinIO themselves, not by the proxy) and logs what it sees independently.
//! That's what this crate is.
//!
//! # Architecture references
//!
//! - `ARCHITECTURE.md` — 5-VM topology (proxy + N replicas + observer)
//!
//! # v1 scope and honest limits
//!
//! - **Single observer VM** per deployment. Multi-observer quorum is future work.
//! - **Deployment chain only** — the observer doesn't do per-user chain
//!   resolution (that requires the proxy's schema config). The verification
//!   task compares deployment chain heads, not per-user chains.
//! - **Operation-level comparison** — the proxy records parsed SQL with
//!   admin identity; the observer records raw DML events from the
//!   replication stream. Verification compares operation counts and table
//!   names per time window, not exact hashes (the two chains record
//!   different facets of the same event).
//! - **BLS-verified drand seed for Verifier rotation** — v1 ships drand
//!   BLS verification via `verification::entropy::verify_drand_bls`
//!   against the hardcoded League of Entropy G1 public key. OS random
//!   is the fallback when every drand relay is unreachable.

pub mod chain;
pub mod config;
pub mod http;
pub mod subscribers;
